---
title: NotAquatic
author: NotAquatic Solutions Corp.
email: support@forestry.io
description: 'We do phishing. '
baseurl: "/notaquatic"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
