---
title: NotAquatic
author: NotAquatic Solutions Corp.
email: info@notaquatic.com
description: 'We do phishing. '
baseurl: notaquatic.com
url: www.notaquatic.com
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
