---
title: NotAquatic Solutions
author: NotAquatic Solutions Corp.
email: info@notaquatic.com
description: 'We do phishing. '
baseurl: ''
url: www.notaquatic.com
defaults: []
plugins:
- jekyll-feed
- jekyll-menus
